# Set update schedule for GitHub Actions
name: Codacy Analysis CLI
on:
  push:
    branches: [ main ]
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"